"""Supported programming languages for legacy and modern code ingestion."""

from __future__ import annotations

from pathlib import Path

# Extension -> canonical language id (legacy + modern stacks)
LANGUAGE_EXTENSIONS: dict[str, str] = {
    # --- Legacy mainframe / enterprise ---
    ".cbl": "cobol",
    ".cob": "cobol",
    ".cpy": "cobol",
    ".cobol": "cobol",
    ".jcl": "jcl",
    ".pli": "pl1",
    ".pl1": "pl1",
    ".rpg": "rpg",
    ".rpgle": "rpg",
    ".sqlrpgle": "rpg",
    ".rexx": "rexx",
    ".rex": "rexx",
    ".clj": "clojure",
    ".cljc": "clojure",
    ".cljs": "clojure",
    ".lisp": "lisp",
    ".lsp": "lisp",
    ".cl": "lisp",
    ".scm": "scheme",
    ".ss": "scheme",
    ".pro": "prolog",
    ".abl": "progress",
    ".w": "progress",
    ".prg": "foxpro",
    ".bas": "vb",
    ".frm": "vb",
    ".cls": "vb",
    ".vba": "vba",
    ".vbs": "vbscript",
    ".asp": "asp",
    ".asa": "asp",
    ".inc": "asp",
    ".pas": "pascal",
    ".pp": "pascal",
    ".dpr": "delphi",
    ".dfm": "delphi",
    ".adb": "ada",
    ".ads": "ada",
    ".ada": "ada",
    ".f": "fortran",
    ".for": "fortran",
    ".f77": "fortran",
    ".f90": "fortran",
    ".f95": "fortran",
    ".f03": "fortran",
    ".f08": "fortran",
    ".pl": "perl",
    ".pm": "perl",
    ".t": "perl",
    ".awk": "awk",
    ".tcl": "tcl",
    ".tk": "tcl",
    ".sas": "sas",
    ".do": "stata",
    ".ado": "stata",
    ".abap": "abap",
    ".cobcopy": "cobol",
    # --- Systems / C family ---
    ".c": "c",
    ".h": "c",
    ".cpp": "cpp",
    ".cc": "cpp",
    ".cxx": "cpp",
    ".c++": "cpp",
    ".hpp": "cpp",
    ".hh": "cpp",
    ".hxx": "cpp",
    ".cs": "csharp",
    ".asm": "assembly",
    ".s": "assembly",
    ".nasm": "assembly",
    # --- JVM / CLR ---
    ".java": "java",
    ".kt": "kotlin",
    ".kts": "kotlin",
    ".scala": "scala",
    ".groovy": "groovy",
    ".gradle": "groovy",
    ".vb": "vbnet",
    ".fs": "fsharp",
    ".fsx": "fsharp",
    ".fsi": "fsharp",
    # --- Scripting / dynamic ---
    ".py": "python",
    ".pyw": "python",
    ".pyi": "python",
    ".rb": "ruby",
    ".erb": "ruby",
    ".rake": "ruby",
    ".php": "php",
    ".phtml": "php",
    ".lua": "lua",
    ".r": "r",
    ".R": "r",
    ".m": "matlab",
    ".mlx": "matlab",
    ".mm": "objectivecpp",
    ".jsp": "jsp",
    ".js": "javascript",
    ".jsx": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".coffee": "coffeescript",
    ".litcoffee": "coffeescript",
    ".vue": "vue",
    ".svelte": "svelte",
    ".ex": "elixir",
    ".exs": "elixir",
    ".erl": "erlang",
    ".hrl": "erlang",
    ".hs": "haskell",
    ".lhs": "haskell",
    ".jl": "julia",
    ".nim": "nim",
    ".cr": "crystal",
    ".zig": "zig",
    ".dart": "dart",
    ".gd": "gdscript",
    ".sh": "shell",
    ".bash": "shell",
    ".zsh": "shell",
    ".ksh": "shell",
    ".fish": "shell",
    ".ps1": "powershell",
    ".psm1": "powershell",
    ".psd1": "powershell",
  # --- Modern / infra ---
    ".go": "go",
    ".rs": "rust",
    ".swift": "swift",
    ".sol": "solidity",
    ".v": "verilog",
    ".sv": "systemverilog",
    ".vhd": "vhdl",
    ".vhdl": "vhdl",
    ".tf": "hcl",
    ".hcl": "hcl",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".json": "json",
    ".xml": "xml",
    ".xsl": "xslt",
    ".xslt": "xslt",
    ".sql": "sql",
    ".pls": "sql",
    ".pks": "sql",
    ".pkb": "sql",
    ".as": "actionscript",
    # --- Additional legacy enterprise / mainframe ---
    ".nsn": "natural",
    ".nsp": "natural",
    ".ns7": "natural",
    ".ezt": "easytrieve",
    ".sqr": "sqr",
    ".pcode": "peoplecode",
    ".egl": "egl",
    ".eglb": "egl",
    ".mac": "mumps",
    ".mumps": "mumps",
    ".tal": "tal",
    ".pvt": "tal",
    ".jov": "jovial",
    ".jal": "jovial",
    ".cor": "coral",
    ".cms": "cms2",
    ".lan": "lansa",
    ".usc": "uniface",
    ".bp": "pickbasic",
    ".srw": "powerbuilder",
    ".sru": "powerbuilder",
    ".srd": "powerbuilder",
    ".srf": "powerbuilder",
    ".pbl": "powerbuilder",
    ".pbt": "powerbuilder",
    ".cfm": "coldfusion",
    ".cfc": "coldfusion",
    ".cfml": "coldfusion",
    ".cf": "coldfusion",
    ".clw": "clarion",
    ".hb": "harbour",
    ".ch": "clipper",
    ".4th": "forth",
    ".fth": "forth",
    ".apl": "apl",
    ".dyalog": "apl",
    ".sno": "snobol",
    ".icn": "icon",
    ".sim": "simula",
    ".mod": "modula2",
    ".def": "modula2",
    ".alg": "algol",
    ".algol": "algol",
    ".st": "smalltalk",
    ".e": "eiffel",
    ".plm": "plm",
    ".b": "bcpl",
    ".cbs": "cobolscript",
    ".gsx": "gosu",
    ".livecodescript": "livecode",
    ".oor": "openroad",
    ".ad": "janus",
    # --- Scientific / stats / modeling ---
    ".gms": "gams",
    ".sps": "spss",
    ".sas7bdat": "sas",
    ".ctl": "sas",
    # --- Functional / proof assistants ---
    ".ml": "ocaml",
    ".mli": "ocaml",
    ".re": "reason",
    ".rei": "reason",
    ".purs": "purescript",
    ".idr": "idris",
    ".agda": "agda",
    ".lean": "lean",
    ".thy": "isabelle",
    ".coq": "coq",
    # --- Web / template ---
    ".jspf": "jsp",
    ".tag": "jsp",
    ".haml": "haml",
    ".slim": "slim",
    ".mustache": "mustache",
    ".hbs": "handlebars",
    ".liquid": "liquid",
    ".twig": "twig",
    ".smarty": "smarty",
    ".tpl": "smarty",
    # --- Build / codegen / parsers ---
    ".l": "lex",
    ".ll": "lex",
    ".y": "yacc",
    ".yy": "yacc",
    ".g4": "antlr",
    ".rl": "ragel",
    ".cmake": "cmake",
    ".nix": "nix",
    ".bzl": "starlark",
    ".wat": "wasm",
    ".wast": "wasm",
    # --- More modern languages ---
    ".mojo": "mojo",
    ".chpl": "chapel",
    ".bal": "ballerina",
    ".red": "red",
    ".factor": "factor",
    ".k": "kdb",
    ".q": "kdb",
    ".odin": "odin",
    ".vlang": "vlang",
    ".d": "dlang",
    ".objc": "objectivec",
    ".gemspec": "ruby",
    ".gradle.kts": "kotlin",
    ".ktm": "kotlin",
    ".cshtml": "razor",
    ".razor": "razor",
    ".fsproj": "fsharp",
    ".vbproj": "vbnet",
    ".csproj": "csharp",
    ".props": "msbuild",
    ".targets": "msbuild",
    ".nuspec": "nuget",
    ".resx": "dotnet",
    ".xaml": "xaml",
    ".axaml": "avalonia",
    ".gvy": "groovy",
    ".gy": "groovy",
    ".gsh": "groovy",
    ".nut": "squirrel",
    ".moon": "moonscript",
    ".vala": "vala",
    ".vapi": "vala",
    ".feature": "gherkin",
    ".robot": "robotframework",
    # --- Documentation & prose (legacy READMEs, runbooks, ADRs) ---
    ".md": "markdown",
    ".mdx": "markdown",
    ".markdown": "markdown",
    ".rst": "restructuredtext",
    ".adoc": "asciidoc",
    ".asciidoc": "asciidoc",
    ".org": "orgmode",
    ".tex": "latex",
    ".latex": "latex",
    ".txt": "plaintext",
    ".text": "plaintext",
    ".rtf": "richtext",
    ".pod": "perldoc",
    ".rdoc": "rdoc",
    ".man": "manpage",
    ".1": "manpage",
    ".wiki": "wiki",
    ".creole": "wiki",
    ".mediawiki": "wiki",
    ".ipynb": "notebook",
    ".csv": "csv",
    ".tsv": "csv",
    ".toml": "toml",
    ".ini": "ini",
    ".cfg": "ini",
    ".properties": "properties",
    ".env.example": "dotenv",
    ".editorconfig": "editorconfig",
    ".gitattributes": "gitconfig",
    ".gitignore": "gitconfig",
    ".dockerfile": "dockerfile",
    ".containerfile": "dockerfile",
    ".drawio": "diagram",
    ".puml": "plantuml",
    ".plantuml": "plantuml",
    ".dot": "graphviz",
    ".gv": "graphviz",
    ".mmd": "mermaid",
    ".mermaid": "mermaid",
}

# Human-readable labels for UI
LANGUAGE_LABELS: dict[str, str] = {
    "cobol": "COBOL",
    "jcl": "JCL",
    "pl1": "PL/I",
    "rpg": "RPG",
    "rexx": "REXX",
    "fortran": "Fortran",
    "pascal": "Pascal",
    "delphi": "Delphi",
    "ada": "Ada",
    "perl": "Perl",
    "tcl": "Tcl",
    "awk": "AWK",
    "vb": "Visual Basic",
    "vba": "VBA",
    "vbscript": "VBScript",
    "vbnet": "VB.NET",
    "asp": "Classic ASP",
    "progress": "OpenEdge ABL",
    "foxpro": "FoxPro",
    "sas": "SAS",
    "stata": "Stata",
    "abap": "ABAP",
    "c": "C",
    "cpp": "C++",
    "csharp": "C#",
    "assembly": "Assembly",
    "java": "Java",
    "kotlin": "Kotlin",
    "scala": "Scala",
    "groovy": "Groovy",
    "fsharp": "F#",
    "python": "Python",
    "javascript": "JavaScript",
    "typescript": "TypeScript",
    "ruby": "Ruby",
    "php": "PHP",
    "lua": "Lua",
    "r": "R",
    "matlab": "MATLAB",
    "objectivecpp": "Objective-C++",
    "jsp": "JSP",
    "go": "Go",
    "rust": "Rust",
    "swift": "Swift",
    "solidity": "Solidity",
    "verilog": "Verilog",
    "systemverilog": "SystemVerilog",
    "vhdl": "VHDL",
    "hcl": "HCL/Terraform",
    "sql": "SQL",
    "lisp": "Lisp",
    "scheme": "Scheme",
    "prolog": "Prolog",
    "clojure": "Clojure",
    "elixir": "Elixir",
    "erlang": "Erlang",
    "haskell": "Haskell",
    "julia": "Julia",
    "nim": "Nim",
    "crystal": "Crystal",
    "zig": "Zig",
    "dart": "Dart",
    "gdscript": "GDScript",
    "shell": "Shell",
    "powershell": "PowerShell",
    "coffeescript": "CoffeeScript",
    "vue": "Vue",
    "svelte": "Svelte",
    "actionscript": "ActionScript",
    "yaml": "YAML",
    "json": "JSON",
    "xml": "XML",
    "xslt": "XSLT",
    "natural": "NATURAL",
    "easytrieve": "Easytrieve",
    "sqr": "SQR",
    "peoplecode": "PeopleCode",
    "egl": "IBM EGL",
    "mumps": "MUMPS",
    "tal": "Tandem TAL",
    "jovial": "JOVIAL",
    "coral": "CORAL",
    "cms2": "CMS-2",
    "lansa": "LANSA",
    "uniface": "Uniface",
    "pickbasic": "Pick/BASIC",
    "powerbuilder": "PowerBuilder",
    "coldfusion": "ColdFusion",
    "clarion": "Clarion",
    "harbour": "Harbour",
    "clipper": "Clipper/xBase",
    "forth": "Forth",
    "apl": "APL",
    "snobol": "SNOBOL",
    "icon": "Icon",
    "simula": "Simula",
    "modula2": "Modula-2",
    "algol": "ALGOL",
    "smalltalk": "Smalltalk",
    "eiffel": "Eiffel",
    "plm": "PL/M",
    "bcpl": "BCPL",
    "cobolscript": "CobolScript",
    "gosu": "Gosu",
    "livecode": "LiveCode",
    "openroad": "OpenROAD",
    "janus": "Janus/ADEL",
    "gams": "GAMS",
    "spss": "SPSS",
    "ocaml": "OCaml",
    "reason": "Reason",
    "purescript": "PureScript",
    "idris": "Idris",
    "agda": "Agda",
    "lean": "Lean",
    "isabelle": "Isabelle",
    "coq": "Coq",
    "haml": "Haml",
    "slim": "Slim",
    "mustache": "Mustache",
    "handlebars": "Handlebars",
    "liquid": "Liquid",
    "twig": "Twig",
    "smarty": "Smarty",
    "lex": "Lex/Flex",
    "yacc": "Yacc/Bison",
    "antlr": "ANTLR",
    "ragel": "Ragel",
    "cmake": "CMake",
    "nix": "Nix",
    "starlark": "Starlark",
    "wasm": "WebAssembly",
    "mojo": "Mojo",
    "chapel": "Chapel",
    "ballerina": "Ballerina",
    "red": "Red",
    "factor": "Factor",
    "kdb": "K/Q (kdb+)",
    "odin": "Odin",
    "vlang": "V",
    "dlang": "D",
    "objectivec": "Objective-C",
    "razor": "Razor",
    "msbuild": "MSBuild",
    "nuget": "NuGet",
    "dotnet": ".NET Resources",
    "xaml": "XAML",
    "avalonia": "Avalonia",
    "squirrel": "Squirrel",
    "moonscript": "MoonScript",
    "vala": "Vala",
    "gherkin": "Gherkin",
    "robotframework": "Robot Framework",
    "markdown": "Markdown",
    "restructuredtext": "reStructuredText",
    "asciidoc": "AsciiDoc",
    "orgmode": "Org Mode",
    "latex": "LaTeX",
    "plaintext": "Plain Text",
    "richtext": "Rich Text",
    "perldoc": "POD",
    "rdoc": "RDoc",
    "manpage": "Man Page",
    "wiki": "Wiki",
    "notebook": "Jupyter Notebook",
    "csv": "CSV/TSV",
    "toml": "TOML",
    "ini": "INI/Config",
    "properties": "Java Properties",
    "dotenv": "Env Template",
    "editorconfig": "EditorConfig",
    "gitconfig": "Git Config",
    "dockerfile": "Dockerfile",
    "diagram": "Diagram",
    "plantuml": "PlantUML",
    "graphviz": "Graphviz DOT",
    "mermaid": "Mermaid",
}

# Regex entity extraction patterns per language (name, kind)
ENTITY_PATTERNS: dict[str, list[tuple[str, str]]] = {
    "python": [
        (r"^(?:async\s+)?def\s+(\w+)\s*\(", "function"),
        (r"^class\s+(\w+)", "class"),
    ],
    "javascript": [
        (r"(?:export\s+)?(?:async\s+)?function\s+(\w+)", "function"),
        (r"(?:export\s+)?class\s+(\w+)", "class"),
        (r"(?:export\s+)?const\s+(\w+)\s*=\s*(?:async\s*)?\(", "function"),
    ],
    "typescript": [
        (r"(?:export\s+)?(?:async\s+)?function\s+(\w+)", "function"),
        (r"(?:export\s+)?class\s+(\w+)", "class"),
        (r"(?:export\s+)?interface\s+(\w+)", "interface"),
    ],
    "cobol": [
        (r"PROGRAM-ID\.\s+(\S+)", "program"),
        (r"^\s*(\w+)\s+SECTION\.", "section"),
    ],
    "fortran": [
        (r"(?i)^\s*(?:recursive\s+)?(?:pure\s+)?(?:elemental\s+)?function\s+(\w+)", "function"),
        (r"(?i)^\s*subroutine\s+(\w+)", "subroutine"),
        (r"(?i)^\s*module\s+(\w+)", "module"),
    ],
    "java": [
        (r"(?:public|private|protected)?\s*(?:static\s+)?[\w<>,\s]+\s+(\w+)\s*\(", "method"),
        (r"(?:public|private)?\s*class\s+(\w+)", "class"),
        (r"interface\s+(\w+)", "interface"),
    ],
    "csharp": [
        (r"(?:public|private|protected|internal)?\s*(?:static\s+)?[\w<>,\s]+\s+(\w+)\s*\(", "method"),
        (r"(?:public|private)?\s*class\s+(\w+)", "class"),
        (r"interface\s+(\w+)", "interface"),
    ],
    "c": [
        (r"^[\w\s\*]+\s+(\w+)\s*\([^;]*\)\s*\{", "function"),
        (r"^typedef\s+struct\s+(\w+)", "struct"),
    ],
    "cpp": [
        (r"^[\w\s:<>,\*&]+\s+(\w+)\s*\([^;]*\)\s*(?:const)?\s*\{", "function"),
        (r"^class\s+(\w+)", "class"),
        (r"^struct\s+(\w+)", "struct"),
    ],
    "go": [
        (r"^func\s+(?:\([^)]*\)\s+)?(\w+)", "function"),
        (r"^type\s+(\w+)\s+struct", "struct"),
    ],
    "rust": [
        (r"^fn\s+(\w+)", "function"),
        (r"^struct\s+(\w+)", "struct"),
        (r"^impl\s+(\w+)", "impl"),
    ],
    "ruby": [
        (r"^def\s+(\w+)", "method"),
        (r"^class\s+(\w+)", "class"),
        (r"^module\s+(\w+)", "module"),
    ],
    "php": [
        (r"function\s+(\w+)", "function"),
        (r"class\s+(\w+)", "class"),
    ],
    "perl": [
        (r"^sub\s+(\w+)", "subroutine"),
        (r"^package\s+(\w+)", "package"),
    ],
    "vb": [
        (r"(?i)^\s*(?:Public|Private)?\s*(?:Sub|Function)\s+(\w+)", "routine"),
        (r"(?i)^\s*Class\s+(\w+)", "class"),
    ],
    "vbnet": [
        (r"(?i)^\s*(?:Public|Private)?\s*(?:Sub|Function)\s+(\w+)", "routine"),
        (r"(?i)^\s*Class\s+(\w+)", "class"),
    ],
    "pascal": [
        (r"(?i)^\s*procedure\s+(\w+)", "procedure"),
        (r"(?i)^\s*function\s+(\w+)", "function"),
    ],
    "delphi": [
        (r"(?i)^\s*procedure\s+(\w+)", "procedure"),
        (r"(?i)^\s*function\s+(\w+)", "function"),
    ],
    "ada": [
        (r"(?i)^\s*procedure\s+(\w+)", "procedure"),
        (r"(?i)^\s*function\s+(\w+)", "function"),
        (r"(?i)^\s*package\s+(\w+)", "package"),
    ],
    "rpg": [
        (r"(?i)^\s*D\s+(\w+)", "definition"),
        (r"(?i)^\s*P\s+(\w+)", "procedure"),
    ],
    "pl1": [
        (r"(?i)^\s*(\w+)\s*:\s*proc(?:edure)?", "procedure"),
    ],
    "jcl": [
        (r"//(\w+)\s+JOB", "job"),
        (r"//(\w+)\s+EXEC", "step"),
    ],
    "sql": [
        (r"(?i)create\s+(?:or\s+replace\s+)?procedure\s+(\w+)", "procedure"),
        (r"(?i)create\s+(?:or\s+replace\s+)?function\s+(\w+)", "function"),
        (r"(?i)create\s+(?:or\s+replace\s+)?package\s+(\w+)", "package"),
    ],
    "kotlin": [
        (r"fun\s+(\w+)", "function"),
        (r"class\s+(\w+)", "class"),
    ],
    "scala": [
        (r"def\s+(\w+)", "method"),
        (r"class\s+(\w+)", "class"),
        (r"object\s+(\w+)", "object"),
    ],
    "shell": [
        (r"^(\w+)\s*\(\)\s*\{", "function"),
    ],
    "powershell": [
        (r"function\s+(\w+)", "function"),
    ],
    "matlab": [
        (r"^function\s+.*=\s*(\w+)", "function"),
        (r"^function\s+(\w+)", "function"),
    ],
    "abap": [
        (r"(?i)^\s*METHOD\s+(\w+)", "method"),
        (r"(?i)^\s*CLASS\s+(\w+)", "class"),
    ],
    "swift": [
        (r"func\s+(\w+)", "function"),
        (r"class\s+(\w+)", "class"),
        (r"struct\s+(\w+)", "struct"),
    ],
    "assembly": [
        (r"^(\w+):", "label"),
    ],
    "natural": [
        (r"(?i)^\s*DEFINE\s+(?:DATA\s+)?(\w+)", "data_area"),
        (r"(?i)^\s*DEFINE\s+SUBROUTINE\s+(\w+)", "subroutine"),
    ],
    "rexx": [
        (r"(?i)^\s*(\w+)\s*:\s*procedure", "procedure"),
    ],
    "powerbuilder": [
        (r"(?i)^\s*(?:public\s+)?function\s+\w+\s+(\w+)", "function"),
        (r"(?i)^\s*(?:public\s+)?subroutine\s+(\w+)", "subroutine"),
    ],
    "coldfusion": [
        (r"(?i)<cffunction\s+name=[\"'](\w+)[\"']", "function"),
        (r"(?i)<cfcomponent\s+name=[\"'](\w+)[\"']", "component"),
    ],
    "mumps": [
        (r"^(\w+)\s*\(", "routine"),
    ],
    "clipper": [
        (r"(?i)^\s*(?:static\s+)?function\s+(\w+)", "function"),
        (r"(?i)^\s*procedure\s+(\w+)", "procedure"),
    ],
    "harbour": [
        (r"(?i)^\s*(?:static\s+)?function\s+(\w+)", "function"),
        (r"(?i)^\s*procedure\s+(\w+)", "procedure"),
    ],
    "objectivec": [
        (r"[-+]\s*\([^)]*\)\s*(\w+)", "method"),
        (r"@interface\s+(\w+)", "interface"),
    ],
    "ocaml": [
        (r"^let\s+(\w+)", "function"),
        (r"^type\s+(\w+)", "type"),
    ],
    "dlang": [
        (r"^void\s+(\w+)", "function"),
        (r"^class\s+(\w+)", "class"),
    ],
    "markdown": [
        (r"^#{1,6}\s+(.+)", "section"),
        (r"^\[\[(.+)\]\]", "section"),
    ],
    "restructuredtext": [
        (r"^\.\. (\w+):", "directive"),
        (r"^:([^:]+):", "field"),
    ],
    "asciidoc": [
        (r"^==+\s+(.+)", "section"),
    ],
    "mermaid": [
        (r"^(?:graph|flowchart|sequenceDiagram)\s+(\w+)", "diagram"),
    ],
    "plantuml": [
        (r"^@startuml\s+(\w+)", "diagram"),
    ],
}

# Extensions we intentionally skip (binary, generated, etc.) — shown in dry-run hints
UNSUPPORTED_HINT_EXTENSIONS: frozenset[str] = frozenset(
    {
        ".exe", ".dll", ".so", ".dylib", ".o", ".obj", ".class", ".jar", ".war",
        ".ear", ".zip", ".tar", ".gz", ".7z", ".rar", ".pdf", ".png", ".jpg",
        ".gif", ".ico", ".woff", ".woff2", ".ttf", ".eot", ".bin", ".dat",
        ".pyc", ".pyo", ".min.js", ".min.css", ".map", ".lock",
    }
)


def supported_language_list() -> list[dict[str, str | list[str]]]:
    """Return grouped supported languages for API/UI."""
    by_lang: dict[str, list[str]] = {}
    for ext, lang in LANGUAGE_EXTENSIONS.items():
        by_lang.setdefault(lang, []).append(ext)
    items = []
    for lang_id in sorted(by_lang.keys()):
        items.append({
            "id": lang_id,
            "label": LANGUAGE_LABELS.get(lang_id, lang_id.upper()),
            "extensions": sorted(set(by_lang[lang_id])),
        })
    return items


def detect_language(path: Path) -> str | None:
    """Map a file path to a supported language id."""
    name = path.name.lower()
    if name in ("dockerfile", "containerfile") or name.startswith("dockerfile."):
        return "dockerfile"
    if name in (".gitignore", ".gitattributes", ".editorconfig"):
        return LANGUAGE_EXTENSIONS.get(f".{name.lstrip('.')}") or "gitconfig"

    simple = LANGUAGE_EXTENSIONS.get(path.suffix.lower())
    if simple:
        return simple
    for ext, lang in sorted(LANGUAGE_EXTENSIONS.items(), key=lambda item: len(item[0]), reverse=True):
        if ext.startswith(".") and name.endswith(ext):
            return lang
    return None


def get_entity_patterns(language: str) -> list[tuple[str, str]]:
    return ENTITY_PATTERNS.get(language, [])
